# Generated by Django 3.0.8 on 2022-04-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220410_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
