# Generated by Django 3.0.8 on 2022-05-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfields',
            name='fieldType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.FieldTypes'),
        ),
    ]
