# Generated by Django 3.0.8 on 2022-05-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20220512_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfields',
            name='background',
            field=models.CharField(default='', max_length=256),
        ),
    ]
