# Generated by Django 3.0.8 on 2022-05-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formfields_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfields',
            name='background',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
