# Generated by Django 3.0.8 on 2022-05-13 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20220512_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Forms')),
            ],
            options={
                'verbose_name_plural': 'WorkFlow',
            },
        ),
        migrations.CreateModel(
            name='WorkFlowStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=256)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='forms.WorkFlow')),
            ],
            options={
                'verbose_name_plural': 'WorkFlowStates',
            },
        ),
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromState', to='forms.WorkFlowStates')),
                ('toState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toState', to='forms.WorkFlowStates')),
            ],
            options={
                'verbose_name_plural': 'StateTransition',
            },
        ),
    ]
