# Generated by Django 3.0.8 on 2022-05-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_department_roles'),
        ('forms', '0005_department_roles_statetransition_workflow_workflowstates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolesAllowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Roles')),
                ('transtion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowedRoles', to='forms.StateTransition')),
            ],
            options={
                'verbose_name_plural': 'TransitionRoles',
            },
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
