# Generated by Django 3.0.8 on 2022-05-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20220513_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=250)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('currentState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activeforms', to='forms.WorkFlowStates')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formInstances', to='forms.Forms')),
            ],
        ),
        migrations.CreateModel(
            name='FormFieldData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000)),
                ('fieldId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldData', to='forms.FormFields')),
                ('formInst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formData', to='forms.FormInstance')),
            ],
        ),
    ]
