# Generated by Django 3.0.8 on 2022-05-14 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_formfielddata_forminstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfielddata',
            options={'verbose_name_plural': 'FormFieldData'},
        ),
        migrations.AlterModelOptions(
            name='forminstance',
            options={'verbose_name_plural': 'FormInstances'},
        ),
        migrations.CreateModel(
            name='WorkflowData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=250)),
                ('formInst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowdata', to='forms.FormInstance')),
                ('transitions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.StateTransition')),
            ],
        ),
    ]
