# Generated by Django 3.0.8 on 2022-05-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_formfielddata_forminstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfielddata',
            options={'verbose_name_plural': 'FormFieldData'},
        ),
        migrations.AlterModelOptions(
            name='forminstance',
            options={'verbose_name_plural': 'FormInstances'},
        ),
    ]
