# Generated by Django 3.0.8 on 2022-05-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20220514_1045'),
        ('forms', '0008_auto_20220514_1202'),
    ]

    operations = [
    ]
